---
- name: Install Remi yum repository for CentOS 6
  yum: name="http://rpms.remirepo.net/enterprise/remi-release-6.rpm"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  tags:
    - epel

- name: Install EPEL yum repository for CentOS 7
  yum: name="http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - epel
