---
- name: Execute composer
  composer: command=install working_dir={{ setup_application_root }} no_dev=no

- name: Copy .env.example to .env
  command: cp -a .env.example .env chdir={{ setup_application_root }}

- name: Migrate databse
  command: php artisan migrate --env={{ setup_application_laravel_env }} chdir={{ setup_application_root }}

- name: Import seed data
  command: php artisan db:seed --env={{ setup_application_laravel_env }} chdir={{ setup_application_root }}

- name: Execute application test
  command: php vendor/bin/phpunit chdir={{ setup_application_root }}
